services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: petshop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
 
  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

volumes:
  pgdata:

  # docker exec -it 287a5c98720a bash
  # psql -U user -d student
